server:
  port: 8081

spring:
  application:
    name: microservice-config-client
  cloud:
    config:
      uri: http://localhost:8000/
      profile: master
      label: master
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
